# Generated by Django 5.0.7 on 2024-08-09 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_home', '0002_faq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
