# Generated by Django 5.0.7 on 2024-08-09 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_home', '0004_alter_comment_user_alter_ticket_assigned_to_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, default='Support', max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
