# Generated by Django 5.0.7 on 2024-08-09 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_home', '0005_supportmember'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportmember',
            name='user_mode',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='supportmember',
            name='user_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
